name: Build, Push Docker Image and Deploy with Pulumi

on:
  push:
    branches:
      - main

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest

    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_IMAGE_NAME: akkharaphopmakanat/test-go-app

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t $DOCKER_IMAGE_NAME:latest .
        docker push $DOCKER_IMAGE_NAME:latest

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Pulumi CLI
      uses: pulumi/actions@v4

    - name: Install NPM dependencies
      run: npm install

    - name: Set up Pulumi stack
      run: |
        pulumi stack select dev || pulumi stack init dev

    - name: Pulumi up
      run: pulumi up --yes
